//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 01 17:59:09 EEST 2012
//----------------------------------------------------

package sa;

/** CUP generated interface containing symbol constants. */
public interface SymbolsInfo {
  /* terminals */
  public static final int CHAR_TYPE = 4;
  public static final int DIVIDE = 28;
  public static final int SYSTEM_IN_READ = 41;
  public static final int BOOLEAN_KEYWORD = 9;
  public static final int LEFT_FIG_PARENTHESIS = 49;
  public static final int NOT_EQUAL = 35;
  public static final int LOWER = 29;
  public static final int GREATER = 31;
  public static final int MAIN_KEYWORD = 15;
  public static final int MINUS = 25;
  public static final int INSTANCEOF = 33;
  public static final int SEMICOLON = 43;
  public static final int AND = 37;
  public static final int PUBLIC_KEYWORD = 17;
  public static final int OR = 38;
  public static final int COMMA = 44;
  public static final int RIGHT_PARENTHESIS = 48;
  public static final int NEW_KEYWORD = 16;
  public static final int PLUS = 24;
  public static final int ASSIGN = 39;
  public static final int EXCLAMATION = 36;
  public static final int EOF = 0;
  public static final int EQUAL = 34;
  public static final int STRING_TYPE = 5;
  public static final int GREATER_EQUAL = 32;
  public static final int error = 1;
  public static final int BREAK = 42;
  public static final int INTEGER_TYPE = 2;
  public static final int RIGHT_FIG_PARENTHESIS = 50;
  public static final int RIGHT_SQUARE_PARENTHESIS = 46;
  public static final int TIMES = 27;
  public static final int LEFT_SQUARE_PARENTHESIS = 45;
  public static final int SYSTEM_OUT_PRINTLN = 40;
  public static final int STOP = 23;
  public static final int FLOAT_KEYWORD = 12;
  public static final int RETURN_KEYWORD = 18;
  public static final int STATIC_KEYWORD = 19;
  public static final int WHILE_KEYWORD = 22;
  public static final int LOWER_EQUAL = 30;
  public static final int INT_KEYWORD = 14;
  public static final int CLASS_KEYWORD = 8;
  public static final int STRING_KEYWORD = 20;
  public static final int CHAR_KEYWORD = 10;
  public static final int UNARY_MINUS = 26;
  public static final int VOID_KEYWORD = 21;
  public static final int IF_KEYWORD = 13;
  public static final int ELSE_KEYWORD = 11;
  public static final int FLOAT_TYPE = 3;
  public static final int LEFT_PARENTHESIS = 47;
  public static final int BOOLEAN_TYPE = 6;
  public static final int IDENTIFIER = 7;

  /* non terminals */
  static final int method_call = 27;
  static final int params_list_declaration = 12;
  static final int statement = 18;
  static final int method_declaration = 10;
  static final int if_statement = 20;
  static final int type = 24;
  static final int main_class = 2;
  static final int class_declaration = 6;
  static final int main_class_methods_declaration = 3;
  static final int while_statement = 21;
  static final int param_declaration = 13;
  static final int assignment_statement = 19;
  static final int classes_declaration = 5;
  static final int block = 14;
  static final int goal = 0;
  static final int compilation_unit = 1;
  static final int method_params_declaration = 11;
  static final int reference_type = 25;
  static final int expression = 26;
  static final int variable_declaration = 16;
  static final int actual_params_list = 28;
  static final int methods_declaration = 9;
  static final int output_statement = 23;
  static final int main_method_declaration = 4;
  static final int variables_declaration = 15;
  static final int field_declaration = 8;
  static final int statements = 17;
  static final int method_call_statement = 22;
  static final int fields_declaration = 7;
}

